### PR TITLE
support setting thread factory for batch processor

### PR DESCRIPTION
**Pull request by jiafu1115**
[Motivation]

batch processor's thread can't be set with name or isDamen and so on. It is hard to figure out which thread is for influxdb and take some customized actions.

[Modifications]
add thread factory into processor's builder class and all another method for enable batch.

[Result]
the batch processor's thread can be customized.

### CODE REVIEW

**Comment by majst01** [comment]
Hi @jiafu1115 

This pull request does:
- not have any description what is the purpose or a description what problem it solves,
- not pass unit tests

so i cant merge it

**Comment by jiafu1115** [comment]
@majst01  I am fixing the unit tests and the PR is similar with #79. Thus, #79 is out of date (one year ago) and conflict now.

**Comment by jiafu1115** [comment]
the purpose or a description what problem it solves,
we need know the thread name for trouble shooting so we need we can set it by thread factory
we need set the thread to damen to auto close the batch processor
we need other function which can involved by thread factory.

**Comment by jiafu1115** [comment]
@majst01 done with fix build error and missed description of this PR! 
Thanks!

**Comment by jiafu1115** [comment]
@majst01 done with fix build error and missed description of this PR! 
Thanks!

**Comment by majst01** [comment]
looks good now.

**Pull request merged**
