### PR TITLE
fix(readme): add link to latest client lib

### PR DESCRIPTION
**Pull request by rhajek**

### CODE REVIEW

**Comment by majst01** [comment]
Hi @rhajek,

i am happy to merge this, but i asked @ivankudibal multiple times to release the current state of influxdb-java with no reaction since month. 
So please release the actual master to maven-central as 2.6, after that i will merge this.

**Comment by majst01** [comment]
I dont understand why this is required for a release, there is no dependency, but to bring this to an end i merge this.

**Comment by bednar** [comment]
The client v2.16 is released...

**Comment by majst01** [comment]
takes a while to be visible on maven central, right:
https://mvnrepository.com/artifact/org.influxdb/influxdb-java

**Pull request merged**
