### PR TITLE
BatchProcessor exception handling so that scheduler is not cancelled after connection error

### PR DESCRIPTION
**Pull request by mmatloka**
See https://github.com/influxdata/influxdb-java/issues/143

### CODE REVIEW

**Comment by mmatloka** [comment]
@majst01 ??

**Comment by mmatloka** [comment]
@beckettsean ?

**Comment by beckettsean** [comment]
@mmatloka, let's wait a bit more for @majst01 to respond. InfluxData does not maintain this repo.

**Comment by majst01** [comment]
Hi,
still alive, sorry for the delay, im quite bussy.

Any chance to add a unit test to verify that your code works, other than that seems correct and obviously needed.

**Comment by andrewdodd** [comment]
This is essentially the same change that was supplied in https://github.com/influxdata/influxdb-java/pull/119 but with data loss instead of potential OOM.

I think there are some key 'feature' questions that need answers before you can really decide to include this. I have made a (unfortunately long) issue discussing this at #148.

**Comment by mmatloka** [comment]
@majst01 sure, I'll add the tests!

**Comment by mmatloka** [comment]
Hey @majst01,
I have added the test case.

**Comment by andrewdodd** [comment]
I've changed my mind. I think including this is reasonable (though I'll admit I'm wary of pokemon exception handling). I think it is a simple enough change to include for now.

**Pull request merged**
