### PR TITLE
Using thread-safe data structures in Point class

### PR DESCRIPTION
**Pull request by Rajind**
Changes made to Point class. Changed tag Map to ConcurrentSkipListMap which is thread safe and also supports natural ordering. Changed tag Map to ConcurrentHashMap. (Regarding the issue #170) 
https://github.com/influxdata/influxdb-java/issues/170

### CODE REVIEW

**Comment by majst01** [comment]
Hi,

please add a unit test to show all is still working and thread safety is given.

**Comment by andrewdodd** [comment]
Hi guys,

I'm not convinced this is a necessary change. Replacing the underlying map will (may) fix the threading issues @Rajind  is facing, but everyone will pay the performance penalty. I feel like it would probably be easier for @Rajind  to put some locks in his own code.

Just my 2 cents.
A.

**Comment by caoli5288** [comment]
@andrewdodd I agree:+1

**Comment by majst01** [comment]
@andrewdodd god catch +1 NAK

Closing this PR

**Pull request closed without merging**
