### PR TITLE
InfluxDB-Java Chunking

### PR DESCRIPTION
**Pull request by andyflury**
Adds support for Chunking, see https://docs.influxdata.com/influxdb/v1.1/guides/querying_data/#chunking

If chunking is enabled multiple QueryResults are delivered through a streaming connection. 

I added a new query method to InfluxDBService that takes a consumer that will process received QueryResults. An example call would look like this.

`        influxDB.query(query, 20, queryResult -> System.out.println(queryResult));`

Would you consider integration this code into master?

### CODE REVIEW

**Comment by majst01** [comment]
Looks good but code-coverage decreased which is not good. Can you please add some more corner cases to you unit-test ?

**Comment by majst01** [comment]
OK, Tests are failing because we support influxdb since 0.13, and 0.13 and 1.0 dont have chunking available. So the call to chunked query must result in a proper exception to the caller.

**Comment by andyflury** [comment]
Not sure how to cover those remaining edge cases. 

- The onFailure (line 377) is "invoked when a network exception occurred talking to the server or when an unexpected exception occurred creating the request or processing the response".  And I have no idea how to force that in CI. 
- And fromJson throws and IOException (line 371) in case the body cannot be parsed into a QueryResult. And again I cannot think of any way how to force that

**Comment by majst01** [comment]
Ok, i will take that, can you before i merge add a changelog entry and a Example howto use this feature.

Thanks for contributing

**Comment by andyflury** [comment]
I have no idea why tests are failing now, they passed before and I only updated the CHANGELOG and README. All tests pass locally using 10.13, 1.0 and 1.0

**Comment by majst01** [comment]
Stacktrace is weird, you need to add some logic to unit-test to nail down this problem. I cant merge if we have failing tests.

**Comment by andyflury** [comment]
ok, got it, need to make sure the DB did not get deleted before reading

**Comment by majst01** [comment]
Fine, thanks for your contribution !

**Comment by joelmarty** [comment]
There is an "issue" with this, the chunking implementation uses java 8 features (java.util.function.Consumer) but the pom.xml and the readme were not updated to reflect this change.

Since this feature breaks the java 7 support, I would expect some sort of public notice.

**Comment by majst01** [comment]
Huh, this was my fault, i didnt notice. I thought id wouldnt compile if some Java8 feature are used because compiler is set to Java7 as well in the pom.xml even for tests.

So what did i miss ?

**Comment by andyflury** [comment]
To keep compatibility with Java 7 we could substitute the java.util.function.Consumer with a new Interface e.g. org.influxdb.dto.QueryResultConsumer

**Pull request merged**
