### PR TITLE
Added an option to enable dropping of new points written after action queue exhaustion.

### PR DESCRIPTION
**Pull request by simarpreets**
Fix for #688

### CODE REVIEW

**Comment by majst01** [comment]
Build fails because of checkstyle errors, if these are fixed i can start reviewing

**Comment by simarpreets** [comment]
@majst01 CI build is passing now, please review.

**Comment by majst01** [comment]
LGTM, can you please add a Changelog entry and a section in the MANUAL.md with an useful example ?

**Comment by simarpreets** [comment]
@majst01 Added a changelog entry and update MANUAL.md.
CI build failed because of some unrelated reason(seems like a network issue), will trigger it again after a while.

**Comment by majst01** [comment]
@simarpreets  Thanks for your contribution !

**Comment by simarpreets** [comment]
@majst01 when are you planning to release this?

**Comment by sjoshid** [comment]
I think this is important change but can I nitpick?? What is the need for `dropActionsOnQueueExhaustion` boolean? I would have preferred to just have `droppedActionHandler`.

If `droppedActionHandler` is set, `dropActionsOnQueueExhaustion` is true. If null `dropActionsOnQueueExhaustion` is false. I hate having this separate flag that is meaningless.

**Pull request merged**
