### PR TITLE
Biconsumer exception callback

### PR DESCRIPTION
**Pull request by csokol**
Alternative implementation of #318

### CODE REVIEW

**Comment by csokol** [comment]
Check it out, @majst01 @kkarski.

If you prefer this implementation, I'll change the readme.

**Comment by majst01** [comment]
Great thanks, i like it.

**Comment by csokol** [comment]
Cool, I've fixed the readme, I think this is ready to be merged.

**Comment by majst01** [comment]
One missing nit: Changelog entry

**Comment by csokol** [comment]
Thanks! It would be nice if you could release a snapshot version so we can
start using the new feature. Is that possible?

Em qui, 11 de mai de 2017 13:29, Stefan Majer <notifications@github.com>
escreveu:

**Comment by majst01** [comment]
I will trigger the people from influxdata because they are only able to push to maven central.

**Comment by csokol** [comment]
@majst01 were the influxdata guys able to release the snapshot?

**Comment by majst01** [comment]
I am in contact with them, please be patient.

**Comment by csokol** [comment]
@majst01 any updates on that? sorry, I don't want to be a pusher but it's been two weeks already :)

If you think it will still take long I'll ship a local jar in our application, just let me know.

**Comment by majst01** [comment]
Im still waiting for the influxdb guys to push to maven central. i will ask again. sorry

**Comment by dmullaney** [comment]
Has there been any progress on getting a release for this feature?

**Comment by majst01** [comment]
it is released !

**Pull request merged**
