### PR TITLE
Added version of query method

### PR DESCRIPTION
**Pull request by Ahimsaka**
InfluxDBResultMapper was recently updated with this version of .toPojo:
  public <T> List<T> toPOJO(final QueryResult queryResult, final Class<T> clazz, final String measurementName)
      throws InfluxDBMapperException {
    return toPOJO(queryResult, clazz, measurementName, TimeUnit.MILLISECONDS);
  }

Adding  InfluxDBMapper.query(final Query query, final Class<T> clazz, String measurementName) to take advantage of the new toPojo variation to map a db with variable measurement names to a POJO. Without this pull, mapping Query to Pojo without @Measurement annotation requires both an InfluxDB instance to fetch the query result and an influxDBMapper instance to map to call toPojo directly.

### CODE REVIEW

**Comment by Ahimsaka** [comment]
Alright well, I don't know how to fix the Codecov situation but as long as the new toPojo signature has coverage this commit should be a-okay. Any humans have any questions or concerns, I am more than happy to talk :)

And fwiw, I have personally seen this Codecov character hold up a liquor store at gunpoint, so I don't know who you really want to be trusting around here.

**Comment by majst01** [comment]
Codecov complains the fact that you added a new public facing method without adding a test. So overall this looks fine, but if you dont mind please add a Simple unit test for this new signature and a a CHANGELOG.md entry

**Comment by Ahimsaka** [comment]
Is there a reason why this signature needs a unit test but InfluxDBMapper.query(Class clazz) doesn't?

I'm not an experienced programmer by any means, but to me it would seem redundant to test a method that doesn't contain any new logic, and only calls 2 methods that are already tested elsewhere. 

I any case, I thought it would be more helpful to write a few lines myself than to open an issue to complain when I noticed that somebody forgot to update this method when they added the new-ish toPojo signature. I've already adjusted my code to work around that oversight, so I don't mind if you decide to close this pull request. Maybe I'll look into it again when I'm finished with my project and have a little more time.

**Comment by majst01** [comment]
If the existing method doesnt have a unit test is this bad as well, i will ensure that i dont get any new functionality without coverage

**Comment by Ahimsaka** [comment]
As long as it's consistent, that's perfectly reasonable. I apologize for the impolite response. This is a very helpful library and I am grateful to you for maintaining it. 

I went ahead and added the test for the new InfluxDBMapper.query signature, and also for the existing signature that I didn't see tested previously. It looks like it has passed the CI tests again, and appeased codecov. Please let me know if there are any other issues and I'll do my best to correct them.

**Comment by majst01** [comment]
Hi, sorry for the delay, can you please fix the merge conflict, i will merge then

**Comment by Ahimsaka** [comment]
Merge conflict in Changelog is resolved

**Comment by Ahimsaka** [comment]
Test that failed is unrelated to the changes in this pull request and only failed in one out of 9 builds. 

[ERROR] Failures: 
[ERROR]   MessagePackBatchOptionsTest>BatchOptionsTest.testJitterDuration:250 expected: <null> but was: <[Series [name=weather, tags=null, columns=[time, humidity, temperature, uv_index], values=[[0, 0.0, 0.0, moderate], [3600000000000, 1.1, 1.0, moderate], [7200000000000, 2.2, 2.0, moderate], [10800000000000, 3.3000000000000003, 3.0, moderate], [14400000000000, 4.4, 4.0, moderate], [18000000000000, 5.5, 5.0, moderate], [21600000000000, 6.6000000000000005, 6.0, moderate], [25200000000000, 7.700000000000001, 7.0, moderate], [28800000000000, 8.8, 8.0, moderate], [32400000000000, 9.9, 9.0, moderate], [36000000000000, 11.0, 10.0, moderate], [39600000000000, 12.100000000000001, 11.0, moderate], [43200000000000, 13.200000000000001, 12.0, moderate], [46800000000000, 14.3, 13.0, moderate], [50400000000000, 15.400000000000002, 14.0, moderate], [54000000000000, 16.5, 15.0, moderate], [57600000000000, 17.6, 16.0, moderate], [61200000000000, 18.700000000000003, 17.0, moderate], [64800000000000, 19.8, 18.0, moderate], [68400000000000, 20.900000000000002, 19.0, moderate]]]]>
[INFO] 
[ERROR] Tests run: 376, Failures: 1, Errors: 0, Skipped: 3

**Pull request merged**
