### PR TITLE
Dynamic UDP target host address

### PR DESCRIPTION
**Pull request by m4ce**
This PR tries to solve #480 by refreshing the target UDP host address every 5m. I am not sure if this is the best approach but that's all I could come up with!

### CODE REVIEW

**Comment by lxhoan** [comment]
Hi @fmachado , I think resolving and caching IP address for datagram is unnecessary (and obviously falls defective this case)
In my opinion, this snippet 
```
datagramSocket.send(new DatagramPacket(bytes, bytes.length, hostAddress, udpPort));
```
hostAddress should be changed to SocketAdress

What do you think ?

**Comment by m4ce** [comment]
@lxhoan, that works well only if one has batching enabled. If batching is disabled,  it will resolve the hostname every time an UDP write is performed. It can result in denial of service to the DNS service if one sends out a lot of metrics in a short interval of time.

**Comment by lxhoan** [comment]
@m4ce, there some other dns caching levels down to the IP layer (at least at JVM and your OS), So I think we can be safe
(for java you can refer to this https://docs.oracle.com/javase/6/docs/technotes/guides/net/properties.html)

Otherwise we must be meticulous when introducing more configuration to influxdb (I mean this one ADDRESS_LOOKUP_INTERVAL)

**Comment by lxhoan** [comment]
Hi @fmachado , if you can arrange time please take a look on it
I think this is a realistic use case that influxdb-java should consider to support

**Comment by fmachado** [comment]
@m4ce as far as I could understand from your issue ticket and this PR, you can solve your problem by adding a parameter `-Dnetworkaddress.cache.ttl=300L` to the JVM (as mentioned by @lxhoan and [here](https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html)).

You can also apply this configuration by calling `Security.setProperty` ([javadoc](https://docs.oracle.com/javase/8/docs/api/java/security/Security.html)) but I don't know what happens with already resolved names.

For the reasons mentioned before, I vote for do not merge this PR.

**Comment by fmachado** [comment]
I'm closing this issue but feel free to reopen it if you think your issue cannot be fixed with the way we mentioned here.

**Comment by m4ce** [comment]
@fmachado , sorry to comment on a close issue. I think you suggestion would only work if we changed the code to be:

```datagramSocket.send(new DatagramPacket(bytes, bytes.length, new InetSocketAddress(hostname,  udpPort)));
```

Just like @lxhoan suggested above.

**Comment by m4ce** [comment]
I see this change was  implemented on Sept 5th. We are good then!

**Pull request closed without merging**
