### PR TITLE
allow to figure out, whether the Point.Builder has any fields

### PR DESCRIPTION
**Pull request by kub**
since the build mehtod contains validation for fields emptiness, there should be also way, how to figure out, whether the Builder contains any fields (to prevent the build method from throwing an exception)

### CODE REVIEW

**Comment by majst01** [comment]
What exact problem are you trying to solve, can you show it in a testcase ? Dont see the point actually.

**Comment by kub** [comment]
I'll try to explain my problem more into the detail, hope it helps: 
as the ```Point``` is constructed by the ```Point.Builder```,  ```Point.Builder#build()``` can be called in different part of the application (different method), than ```Point.Builder#addField```. In such case, there is no way how to avoid ```IllegalArgumentException```, that is thrown from [here](https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/dto/Point.java#L197) in case, that no fields were actually added (e.g. because data of these fields was null). 

It's also convenient for other cases. Imagine e.g. this one:
```Groovy
void reportValues(String value1, String value2, String value3) {
    def builder = Point.measurement(measurement).tag(tags).time(time)

    if(value1 != null) {
        builder.addField(TIMESERIES_1, value1)
    }

    if(value2 != null) {
        builder.addField(TIMESERIES_2, value2)
    }

    if(value3 != null) {
        builder.addField(TIMESERIES_3, value3)
    }

    builder.build() // throws IllegalArgumentException, if all values are null

}
```
... again - there should be a way, how to 'ask' the builder, whether it is ok, to call the ```build``` method or whether it will fail with the ```IllegalArgumentException```.

**Comment by majst01** [comment]
Ok understood, but then you need to add a testcase and a addition to the usage description in the README.md to you MR.

**Comment by kub** [comment]
I've added unit test

I'm not sure about README.md - do you really think, that this small detail should be really added there? Tried to read through it and honestly - I'm not sure where to put it. Also seems to me, that README.md should not go into that level of detail (just for sake of readability) - what do you think?

**Pull request merged**
