### PR TITLE
Delete measurement by tags, drop measurement

### PR DESCRIPTION
**Pull request by andreevym**
add methods in API InfluxDB: 'dropMeasurement' and 'delete'
add check method: testDelete, testDropMeasurement

### CODE REVIEW

**Comment by majst01** [comment]
This needs a rebase, not mergable in the current state, i am also not sure if we should make the api wider ? Could we move this kind of functionality into a seperate api ? What do you guys think ?

**Comment by lxhoan** [comment]
@ivankudibal and I recently discussed that seems this PR is not too necessary

I agree that we should keep the client API thin and consistent to InfluxDB REST API (https://docs.influxdata.com/influxdb/v1.5/tools/api/, where only 'write' and 'query' available for CRUD)

BTW, in my opinion, keeping the client API thin and consistent to InfluxDB REST API can help to reach a common guideline for designing/developing new client API in other programming language/environment

So I propose to close this PR

**Comment by andreevym** [comment]
my team for use "DELETE" is normal and useful, but I got it
If you want, you can move this in utils

**Comment by lxhoan** [comment]
Hi @majst01 , so that means we can close this PR ?

**Pull request closed without merging**
