### PR TITLE
Drop guava runtime dependency

### PR DESCRIPTION
**Pull request by simon04**
Some fuctionality is provided by Java 8, the remaining parts can easily be rewritten.

### CODE REVIEW

**Comment by majst01** [comment]
In general i agree with this, but this PR has to much modifications, changes formatting of lines which are not affected, error messages are different, tests are failing.

If you are trying to improve this i can accept tis.

**Comment by simon04** [comment]
I just fixed the checkstyle issues (which caused the tests to fail). There shouldn't be any unrelated formatting changes, though.

**Comment by majst01** [comment]
Ok looks better, i wait til 2.6 is published to maven repo and we can then consider merging for the next release.

**Comment by simon04** [comment]
Thanks for reviewing this PR and maintaining this Java project! :+1:

**Comment by majst01** [comment]
@simon04 would you please resolve the merge conflict, after that i will merge.

**Comment by simon04** [comment]
Done.

**Pull request merged**
