### PR TITLE
InfluxDB: Add Query with Callbacks

### LINKED ISSUE #368: Query w/ Callback Support
Hi.

I would like to add a query method with callback support (`onResult`, `onFailure`). Would you accept a pull request for that?

Thanks.

### PR DESCRIPTION
**Pull request by shanielh**
Fixes #368

### CODE REVIEW

**Comment by majst01** [comment]
looks good so far, can you add a Changelog.md entry and a description how to use in the Readme ?

**Comment by shanielh** [comment]
Sure. Will get to it today.

**Comment by shanielh** [comment]
@majst01 Let me know if the language is fine and If you want me to squash the commits :+1:

**Comment by shanielh** [comment]
Thanks for merging! 😀

Do you know when is the next version release?

**Pull request merged**
